// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function GetVideoDuration(arg1:string):Promise<number>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function StartCropping(arg1:Array<core.Clip>,arg2:string,arg3:string):Promise<void>;

export function ValidateClip(arg1:core.Clip,arg2:number):Promise<boolean>;
