// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVideoDuration(arg1) {
  return window['go']['main']['App']['GetVideoDuration'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function StartCropping(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartCropping'](arg1, arg2, arg3);
}

export function ValidateClip(arg1, arg2) {
  return window['go']['main']['App']['ValidateClip'](arg1, arg2);
}
